version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: springboot-mysql
    restart: always
    environment:
      MYSQL_DATABASE: fuji_db
      MYSQL_ROOT_PASSWORD: capstone2@se47
      MYSQL_USER: se47
      MYSQL_PASSWORD: capstone2@se47
    ports:
      - "4747:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: